- name: install zookeeper-server
  tags: package
  yum: name=zookeeper-server state=present
  notify:
    - restart zookeeper service

- name: create configuration directory
  tags: config
  file: path={{ etc_folder }}/zookeeper state=directory

- name: setup alternatives link
  tags: config
  alternatives: name=zookeeper-conf link=/etc/zookeeper/conf path={{ etc_folder }}/zookeeper

- name: install template configurations
  tags: config
  template: src=zoo.cfg.j2 dest={{ etc_folder }}/zookeeper/zoo.cfg
  notify:
    - restart zookeeper service

- name: install files configurations
  tags: config
  copy: src={{ item }} dest=/etc/zookeeper/conf/{{ item }}
  with_items:
    - configuration.xsl
    - log4j.properties
  notify:
    - restart zookeeper service

- name: install default configurations
  tags: config
  template: src=default/{{ item }}.j2 dest=/etc/default/{{ item }}
  with_items:
    - zookeeper
  notify:
    - restart zookeeper service

- name: clean zookeeper data directory
  tags: init
  file: dest={{ zookeeper_data_dir }} state=absent
  when: destroy_data

- name: create zookeeper data directory
  tags: config
  file: path={{ zookeeper_data_dir }} state=directory owner=zookeeper group=zookeeper

- name: stop zookeeper
  tags: init
  service:  name=zookeeper-server state=stopped
  when: destroy_data
  notify:
    - restart zookeeper service

- name: init zookeeper directory
  tags: init
  command: service zookeeper-server init
  when: destroy_data
  notify:
    - restart zookeeper service

- name: install myid
  tags: init
  template: src=myid.j2 dest={{ zookeeper_data_dir }}/myid
  when: groups['zookeepernodes']|count > 1 and destroy_data
  notify:
    - restart zookeeper service

