- name: Set Hadoop hdfs-journalnode version
  tags: package
  set_fact:
    hdfs_journalnode_pkg: "{{ 'hadoop-hdfs-journalnode-' + hdfs_journalnode_version if hdfs_datanode_version else 'hadoop-hdfs-journalnode' }}"

- name: install journalnode packages
  tags: package
  yum:  name={{ hdfs_journalnode_pkg }} state=present

- name: destroy data
  tags: init
  file: dest={{ dfs_journalnode_edits_dir }} state=absent
  when: destroy_data

- name: create journal node directories
  tags: config
  file: dest={{ dfs_journalnode_edits_dir }} owner=hdfs group=hdfs state=directory

- name: install default configurations
  tags: config
  template: src=default/{{ item }}.j2 dest=/etc/default/{{ item }}
  with_items:
    - hadoop-hdfs-journalnode

- name: start journalnode services
  tags: service
  service: name=hadoop-hdfs-journalnode state=restarted enabled=yes
