- name: init secondary instance
  tags: init
  command: hdfs namenode -bootstrapStandby
  become: true
  become_user: hdfs
  when: ansible_fqdn != groups['namenodes'][0] and destroy_data
  notify:
    - restart secondary namenode

- meta: flush_handlers

- name: start secondary namenode
  tags: service
  service: name=hadoop-hdfs-namenode state=started enabled=yes
  when: ansible_fqdn != groups['namenodes'][0]
