- name: Set Hadoop hdfs-namenode version
  tags: package
  set_fact:
    hdfs_namenode_pkg: "{{ 'hadoop-hdfs-namenode-' + hdfs_namenode_version if hdfs_namenode_version else 'hadoop-hdfs-namenode' }}"

- name: install namenode package
  tags: package
  yum:  name={{ hdfs_namenode_pkg }} state=present

- name: install namenode default configurations
  template: src=default/{{ item }}.j2 dest=/etc/default/{{ item }}
  with_items:
    - hadoop-hdfs-namenode

- name: destroy data
  tags: init
  command: rm -rf {{ item }}
  with_items: "{{ dfs_namenode_name_dir.replace('file://','').split(',') }}"
  when: destroy_data

- name: create namenode directories
  tags: init
  file: dest={{ item }} owner=hdfs group=hdfs state=directory
  with_items: "{{ dfs_namenode_name_dir.replace('file://','').split(',') }}"

