- name: get resource manager ha state
  tags: test
  command: yarn rmadmin -getServiceState {{ ansible_fqdn }}
  become: true
  become_user: yarn
  register: ha_state
  when: groups['yarnresourcemanager']|count > 1

- name: shutdown active resource manager service
  tags: test
  shell: service hadoop-yarn-resourcemanager stop; sleep 1
  when: groups['yarnresourcemanager']|count > 1 and ha_state is defined and ha_state.stdout.find('active') != -1

- name: test mapreduce
  tags: test
  command: hadoop jar /usr/lib/hadoop-mapreduce/hadoop-mapreduce-examples.jar pi 1 1
  become: true
  become_user: hdfs
  run_once: true

- name: start services
  tags: test
  service: name=hadoop-yarn-resourcemanager state=restarted enabled=yes
  when: groups['yarnresourcemanager']|count > 1 and ha_state is defined and ha_state.stdout.find('active') != -1
