- name: add hbase master init scripts
  tags: config
  copy: src=inits/{{ item }} dest=/etc/rc.d/init.d/{{ item }} mode=0755
  with_items:
    - hbase-thrift
    - hbase-rest
    - hbase-master
  when: "ansible_os_family == 'RedHat'"

- name: create hdfs directories
  command: hdfs dfs {{ item }}
  become: true
  become_user: hdfs
  with_items:
    - -mkdir -p /hbase
    - -chown hbase /hbase

- name: start services
  tags: service
  service: name={{ item }} state=restarted enabled=yes
  with_items:
    - hbase-master
    - hbase-thrift
    - hbase-rest
