- name: add hbase regionserver init script
  tags: config
  copy: src=inits/{{ item }} dest=/etc/rc.d/init.d/{{ item }} mode=0755
  with_items:
    - hbase-regionserver
  when: ansible_os_family == 'RedHat' and hbase_deploy_type == 'tar'

- name: start services
  tags: service
  service: name={{ item }} state=restarted enabled=yes
  with_items:
    - hbase-regionserver

- name: hbase test
  tags: test
  shell: echo -e "create 'ansible_test_table', 'id'\ndisable 'ansible_test_table'\n drop 'ansible_test_table'" | hbase shell
  run_once: true
