- name: add hbase regionserver init script
  tags: config
  copy: src=inits/{{ item }} dest=/etc/rc.d/init.d/{{ item }} mode=0755
  with_items:
    - hbase-regionserver
  when: ansible_os_family == 'RedHat' and hbase_deploy_type == 'tar'

- name: adjust limits for hbase
  tags: config
  copy: src=hbase-limits.conf dest=/etc/security/limits.d/hbase.conf
  notify:
    - restart hbase regionserver service

- name: install template configurations
  tags: config
  template: src={{ item }}.j2 dest=/etc/hbase/conf/{{ item }}
  with_items:
    - hbase-site.xml
    - regionservers
  notify:
    - restart hbase regionserver service

- name: install files configurations
  tags: config
  copy: src={{ item }} dest=/etc/hbase/conf/{{ item }}
  with_items:
    - hadoop-metrics2-hbase.properties
    - hbase-env.cmd
    - hbase-env.sh
    - hbase-policy.xml
    - log4j.properties
  notify:
    - restart hbase regionserver service

- name: install default configurations
  tags: config
  copy: src=default/{{ item }} dest=/etc/default/{{ item }}
  with_items:
    - hbase
  notify:
    - restart hbase regionserver service

- meta: flush_handlers

- name: start services
  tags: service
  service: name=hbase-regionserver state=started enabled=yes

- name: hbase test
  tags: test
  shell: echo -e "create 'ansible_test_table', 'id'\ndisable 'ansible_test_table'\n drop 'ansible_test_table'" | hbase shell
  run_once: true
