- name: edit /etc/hosts
  tags: config
  copy: src=hosts dest=/etc/hosts

- name: add cdh5 repo
  tags: packages
  copy: src=cdh5.repo dest=/etc/yum.repos.d/cdh5.repo

- name: install packages
  tags: packages
  yum: name={{item}} state=present
  with_items:
    - "{{ java_package }}"
    - bigtop-utils

- name: install template configurations
  tags: config
  template: src={{ item }}.j2 dest=/etc/default/{{ item }}
  with_items:
    - bigtop-utils

- name: create directories
  tags: config
  # is this a 'dirname' or just regex_replace? dirname would just strip '/' off the end
  file: path="{{ item | regex_replace('[^/]+/*$','') }}" state=directory owner=root group=root mode=755 follow=yes
  with_items:
    - "{{ zookeeper_data_dir }}"
    - "{{ log_folder }}"
    - "{{ etc_folder }}"

- name: generate services.xml
  tags:
    - config
    - clinit
  local_action: template src="services.xml.j2" dest={{ inventory_dir }}/workdir/services.xml
  run_once: true

- name: generate interfaces index
  tags:
    - config
    - interfaces
  local_action: template src="interfaces.j2" dest={{ inventory_dir }}/workdir/interfaces
  run_once: true

